# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Freecam < Formula
  desc "Free your PTP camera (Canon, Nikon, Sony, Fujifilm, Olympus…) from macOS ptpcamera daemon"
  homepage "https://github.com/joennespreuwers/freecam"
  version "1.0.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/joennespreuwers/freecam/releases/download/v1.0.0/freecam_1.0.0_darwin_amd64.tar.gz"
    sha256 "ff50e8ea3032b3e1db26c6d397b4fdd91affa075e8626ff3685dd40cd3152e1a"

    define_method(:install) do
      bin.install "freecam"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/joennespreuwers/freecam/releases/download/v1.0.0/freecam_1.0.0_darwin_arm64.tar.gz"
    sha256 "fd55408e6c6ff96859bb407743724a78780f1e725fb78e4806ebad12bfb7ee99"

    define_method(:install) do
      bin.install "freecam"
    end
  end

  test do
    system "#{bin}/freecam --version"
  end
end
