# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Freecam < Formula
  desc "Free your PTP camera (Canon, Nikon, Sony, Fujifilm, Olympus…) from macOS ptpcamera daemon"
  homepage "https://github.com/joennespreuwers/freecam"
  version "1.0.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/joennespreuwers/freecam/releases/download/v1.0.0/freecam_1.0.0_darwin_amd64.tar.gz"
    sha256 "c82a0f3221a272e7298d6344566014f099ff17266adea0d327715fd0950e406b"

    define_method(:install) do
      bin.install "freecam"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/joennespreuwers/freecam/releases/download/v1.0.0/freecam_1.0.0_darwin_arm64.tar.gz"
    sha256 "9ab718ae416f684200a0f0f5c772e8f08fc11886131c99e83def72c042ebdc72"

    define_method(:install) do
      bin.install "freecam"
    end
  end

  test do
    system "#{bin}/freecam --version"
  end
end
